module.exports = Object.freeze({
  INCREMENT_VALUE_BY_LIKE : 2,
  INCREMENT_VALUE_BY_SHARE : 3,
  INCREMENT_VALUE_BY_COMMENT : 3,

  WEIGHT_TIME_WATCH_IN_BEST_CAT: 2,
  
  POINTBREAK_TIME_WATCH_1 : 50,
  POINTBREAK_TIME_WATCH_2 : 70,
  POINTBREAK_TIME_WATCH_3 : 90,
  POINTBREAK_TIME_WATCH_4 : 100,
  INCREMENT_VALUE_1_POINTBREAK : 2,
  INCREMENT_VALUE_2_POINTBREAK : 3,
  INCREMENT_VALUE_3_POINTBREAK : 4,
  INCREMENT_VALUE_4_POINTBREAK : 5,

  COLLECTION_NAME_VIDEO: 'video',
  COLLECTION_NAME_PROFILATION: 'user',
  DATABASE_NAME: 'youtube'
})  